### PR TITLE
a bunch of Trådfri things as well as an Osram outlet

### PR DESCRIPTION
**Pull request by k4mrat**
Added:

*Trådfri remote 5 buttons

*Trådfri square dimmer (also known as on/off, but listed as dimmer by IKEA and has dim capabilities)

*Trådfri outlet

*Trådfri motion sensor v1 (this has a basic boolean lux meter "dark: true/false" that would be cool to use, but I can't get it to work right now.)

*Osram Outlet

*as well as Skorpions good work with the Symfonisk remote!

*In here is also the Tradfri Round Dimmer that is behaving like crap! So i added its drivers but havent been able to map the buttons correctly. It should be something like the Symfonisk (cw turn start/stopp, ccw turn start/stop), but i really wouldnt bother with it unless someone specifically requests it and their life depends on it...

### CODE REVIEW

**Comment by notabene00** [comment]
About Tradfri round dimmer, there's no stops
Its codes are:
`1002` for sharp counter clockwise turn
`2002` for slow counter clockwise turn
`3002` for slow clockwise turn
`4002` for sharp clockwise turn
it's already implemented and will be pushed soon
___
What about "boolean lux meter"?
What data it posts to the websocket?
Post here, then I'll help

I think that we should create a custom capability for binary luminance sensor
Then we'll can get it working too

**Comment by k4mrat** [comment]
Tradfri round:

Ok! When I had them native in Homey they stated start/stop, that’s why I called them like that :) I have trouble using them at all. Paired three of them and they seem to log events for a while but then die. Looking forward to try them with working code! I think that IKEA stopped selling them due to this kind of behavior though. 


Motion:
Sounds good! I’ll try to look in to it tonight or this weekend!

**Comment by notabene00** [comment]
@k4mrat tradfri round dimmer is here if you wanna know :)

**Comment by notabene00** [comment]
@k4mrat 

* Please check if outlets (Tradfri and Osram) already works as `Plug`

* Symfonisk remote and Tradfri round dimmer are supported, you can test them too

* Tradfri motion sensor waits to be fully implemented including its binary luminance sensor
I can help, but I need its report data
You may use issues for device request
There are a template for it and info about what data is necessary

* Trådfri remote 5 buttons and Trådfri on/off dimmer are looking good
I'll merge if you create a PR with these two

**Comment by k4mrat** [comment]
I couldn’t get any outlet to work, that’s why I started adding stuff :) But I’ll check! Maybe it’s possible to use one driver and just filter them to different icons? I personally likes to see the brand/icon of my different plugs :)

I’ll take a look at the motion sensor tonight when I get off work and make a PR with only 5 and onoff.

**Comment by notabene00** [comment]
> Maybe it’s possible to use one driver and just filter them to different icons

ye, AFAIK, it is possible

> I couldn’t get any outlet to work, that’s why I started adding stuff :) But I’ll check!

try >= 0.6.0, @SkorpionNL there defined another type of plugs
https://github.com/fantomnotabene/HomeyCONZ/blob/76e2b1562df7de89068cbbc53a6930ac59b21744/drivers/plug/driver.js#L13

**Comment by SkorpionNL** [comment]
I can confirm that the Osram plug and INNR SP120 do work with my commit in 0.6.0 that @fantomnotabene mentioned. The INNR SP110 already worked.

**Pull request closed without merging**
