### PR TITLE
tradfri 5button and tradfri square dimmer

### PR DESCRIPTION
**Pull request by k4mrat**
Sorry for the delay, it took me ages figuring out that i had missed the "trigger" section in app.json and that it was the reason for the app constantly crashing on me and then I had a weird Deconz crash as well.

Both 5-button and square dimmer should be up and running now.

Added an "angled" icon to the square dimmer that I think look really good and i'm thinking of putting up some new icons for some of the other Trådfri as well for your review.

Haven't figured out how I could possibly filter different plugs/outlets to different icons based on their device.id while still using the same driver. If you feel like taking a look at that possibility i'm more than happy to add some more icons to the plug/outlet category as well, but I can't for the life of me figure it out.

### CODE REVIEW

**Comment by notabene00** [comment]
> Haven't figured out how I could possibly filter different plugs/outlets to different icons based on their device.id

You can set an icon inside of the device object when pairing here:
https://github.com/fantomnotabene/HomeyCONZ/blob/76e2b1562df7de89068cbbc53a6930ac59b21744/drivers/Driver.js#L61

Example:
https://github.com/jghaanstra/com.xiaomi-miio/blob/9c95f4a521aa3c6e834212c19fc7e9d9bfc73d57/drivers/yeelights/driver.js#L94

**Review by notabene00 — CHANGES_REQUESTED** [review]
Get rid of _DS_Store files.

If you're working on a mac or linux-based system, you can just `cd` to local repository and run `find . -name _DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch`.

**Comment by notabene00** [comment]
My bad, I was not pay attention to where the files are, but.. why are your drivers in the root project directory?)
Fixed here now, version bumped

**Comment by k4mrat** [comment]
> 
> 
> My bad, I was not pay attention to where the files are, but.. why are your drivers in the root project directory?)

because i'm a damn noob and late for work and i stressed the upload. Super sorry about that!

**Comment by notabene00** [comment]
Not a big problem really. Fixed already.
So I'm waiting for hue motion sensor's data.

You can help here: #7

**Comment by notabene00** [comment]
Oh, I've been confused.. Hue motion sensor
I'll create an issue for Tradfri motion sensor now

**Comment by notabene00** [comment]
Found necessary data #14

**Pull request merged**
